module.exports = {
    "SUCCESS": "Operation completed successfully",
    "ERROR": "An error occurred during the operation",
    "USER_NOT_FOUND": "User not found",
    "INVALID_CREDS": "Invalid credentials provided",
    "TOKEN_NOT_FOUND": "Authentication token not found",
    "INVALID_TOKEN": "The provided token is invalid",
    "EMAIL_EXISTS": "Email already exists",
    "USER_REGISTERED_SUCCESSFULLY": "User registered successfully",
    "ERROR_REGISTERING_USER": "An error occurred while registering the user",
    "USER_DELETED_SUCCESSFULLY": "User deleted successfully",
    "TOPICS_NOT_FOUND": "No topics found for the user",
    "TOPIC_NOT_FOUND": "Topic not found",
    "TOPIC_FETCHED_SUCCESSFULLY": "Topics fetched successfully",
    "ERROR_CREATING_TOPIC": "An error occurred while creating the topic",
    "TOPIC_CREATED_SUCCESSFULLY": "Topic created successfully",
    "TOPIC_UPDATED_SUCCESSFULLY": "Topic updated successfully",
    "ERROR_UPDATING_TOPIC": "An error occurred while updating the topic",
    "TOPIC_DELETED_SUCCESSFULLY": "Topic deleted successfully",
    "ERROR_DELETING_TOPIC": "An error occurred while deleting the topic",
    "POST_NOT_FOUND": "Post not found",
    "POST_FETCHED_SUCCESSFULLY": "Post fetched successfully",
    "ERROR_CREATING_POST": "An error occurred while creating the post",
    "POST_CREATED_SUCCESSFULLY": "Post created successfully",
    "POST_UPDATED_SUCCESSFULLY": "Post updated successfully",
    "ERROR_UPDATING_POST": "An error occurred while updating the post",
    "POST_DELETED_SUCCESSFULLY": "Post deleted successfully",
    "ERROR_DELETING_POST": "An error occurred while deleting the post",
    "POSTS_NOT_FOUND": "No posts found",
    "POSTS_FETCHED_SUCCESSFULLY": "Posts fetched successfully",
    "POSTS_BY_TOPIC_FETCHED_SUCCESSFULLY": "Posts fetched successfully for the topic",
    "POSTS_BY_USER_FETCHED_SUCCESSFULLY": "Posts fetched successfully for the user",
    "POST_FOUND": "Post Fetched Successfully",
    "ERROR_FETCHING_POSTS_BY_TOPIC": "An error occurred while fetching posts by topic",
    "ERROR_FETCHING_POSTS_BY_USER": "An error occurred while fetching posts by user",
    "ERROR_FETCHING_POST": "An error occurred while fetching the post",    
}