module.exports = {
    "SUCCESS": "Operation completed successfully",
    "ERROR": "An error occurred during the operation",
    "USER_NOT_FOUND": "User not found",
    "INVALID_CREDS": "Invalid credentials provided",
    "TOKEN_NOT_FOUND": "Authentication token not found",
    "INVALID_TOKEN": "The provided token is invalid",
    "EMAIL_EXISTS": "Email already exists",
    "USER_REGISTERED_SUCCESSFULLY": "User registered successfully",
    "ERROR_REGISTERING_USER": "An error occurred while registering the user",
    "USER_DELETED_SUCCESSFULLY": "User deleted successfully",
    "TOPICS_NOT_FOUND": "No topics found for the user",
    "TOPIC_NOT_FOUND": "Topic not found",
    "TOPIC_FETCHED_SUCCESSFULLY": "Topics fetched successfully",
    "ERROR_CREATING_TOPIC": "An error occurred while creating the topic",
    "TOPIC_CREATED_SUCCESSFULLY": "Topic created successfully",
    "TOPIC_UPDATED_SUCCESSFULLY": "Topic updated successfully",
    "ERROR_UPDATING_TOPIC": "An error occurred while updating the topic",
    "TOPIC_DELETED_SUCCESSFULLY": "Topic deleted successfully",
    "ERROR_DELETING_TOPIC": "An error occurred while deleting the topic",
    "POST_NOT_FOUND": "Post not found",
    "POST_FETCHED_SUCCESSFULLY": "Post fetched successfully",
    "ERROR_CREATING_POST": "An error occurred while creating the post",
    "POST_CREATED_SUCCESSFULLY": "Post created successfully",
    "POST_UPDATED_SUCCESSFULLY": "Post updated successfully",
    "ERROR_UPDATING_POST": "An error occurred while updating the post",
    "POST_DELETED_SUCCESSFULLY": "Post deleted successfully",
    "ERROR_DELETING_POST": "An error occurred while deleting the post",
    "POSTS_NOT_FOUND": "No posts found",
    "POSTS_FETCHED_SUCCESSFULLY": "Posts fetched successfully",
    "POSTS_BY_TOPIC_FETCHED_SUCCESSFULLY": "Posts fetched successfully for the topic",
    "POSTS_BY_USER_FETCHED_SUCCESSFULLY": "Posts fetched successfully for the user",
    "POST_FOUND": "Post Fetched Successfully",
    "ERROR_FETCHING_POSTS_BY_TOPIC": "An error occurred while fetching posts by topic",
    "ERROR_FETCHING_POSTS_BY_USER": "An error occurred while fetching posts by user",
    "ERROR_FETCHING_POST": "An error occurred while fetching the post",    
    "IMAGE_UPLOADED_SUCCESSFULLY": "Image uploaded successfully",
    "ERROR_UPLOADING_IMAGE": "An error occurred while uploading the image",
    "IMAGE_NOT_UPLOADED": "No image uploaded",
    "ERROR_SAVING_IMAGE": "An error occurred while saving the image",
    "ACTIVITY_CREATED_SUCCESSFULLY": "Activity created successfully",
    "ERROR_CREATING_ACTIVITY": "An error occurred while creating the activity",
    "ACTIVITY_NOT_FOUND": "Activity not found",
    "ACTIVITY_FETCHED_SUCCESSFULLY": "Activity fetched successfully",
    "ACTIVITIES_FETCHED_SUCCESSFULLY": "Activities fetched successfully",
    "ERROR_FETCHING_ACTIVITIES": "An error occurred while fetching activities",
    "ACTIVITY_UPDATED_SUCCESSFULLY": "Activity updated successfully",
    "ERROR_UPDATING_ACTIVITY": "An error occurred while updating the activity",
    "ACTIVITY_DELETED_SUCCESSFULLY": "Activity deleted successfully",
    "ERROR_DELETING_ACTIVITY": "An error occurred while deleting the activity",
    "LIKE_ACTIVITY_DELETED_SUCCESSFULLY": "Like activity deleted successfully",
    "FAILED TO CREATE ACTIVITY": "Failed to create activity",
    "NO_ACTIVITIES_FOUND_FOR_THIS_POST": "No activities found for this post",
    "NO_ACTIVITIES_FOUND_FOR_THIS_USER": "No activities found for this user",
    "ACTIVITY ID AND UPDATED DATA ARE REQUIRED": "Activity ID and updated data are required",
    "ACTIVITY ID IS REQUIRED": "Activity ID is required",
}